# Copyright 2010 Yiyuan Zhong, Shanghai Jiao Tong University. All Rights Reserved.
# Author: yiyuanzhong@gmail.com (Yiyuan Zhong)

### MODIFY ANYTHING BELOW THIS LINE THAT IS SUITABLE ###

#CXX=$(CC)

TARGET = ../../bin/jail

SUBDIRS = .

STATICS += op/oped/noah/sailor/utility/output/lib/sailor_utility
LIBRARIES += rt ullib

MODULEROOT = ../../../../../..
MODULEPATH = inf/computing/matrix/matrix-agent/tools/jail

BINPATH =

SEARCHPATH = op/oped/noah/sailor/utility/output/include

LIBRARYPATH = $(LIB2)/ullib/lib

# Installing related
DESTDIR =
prefix = /usr
EXTRA_INSTALLS =

### MODIFY ANYTHING BELOW THIS LINE CAREFULLY ###

CROSS_COMPILE =

### DON'T MODIFY ANYTHING BELOW THIS LINE ###

GOAL = $(EXECUTABLE)
GOALd = $(EXECUTABLEd)

include $(MODULEROOT)/op/oped/noah/sailor/utility/include.mk
